[project]
name = "movie-project-part-2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "colorama>=0.4.6",
    "matplotlib>=3.10.3",
]
